Repository kartikeysingh6/OpenCVProjects, pull requests merged in 2021-10, with the labels that each got.

#1 Update video.py
  Basic/Vido and Webcam/video.py
Labels: good first issue, hacktoberfest-accepted

#2 Added An OpenCV Project
  Unknown Face Detection Email Sending Software/FaceDetectingEmail.py.txt
  Unknown Face Detection Email Sending Software/haarcascade_frontalface_default.xml
Labels: enhancement, good first issue, hacktoberfest-accepted

#3 Update ShapeWebcam.py
  ShapeDetector/ShapeWebcam.py
Labels: enhancement, hacktoberfest-accepted

#4 KadeneAlgorithm
  FeatureDetection/KadaneAlgo.cpp
Labels: hacktoberfest-accepted
